// Canonical catalog copied from iporollo/addictinggames.ai at c2b7d91.
// Keep original metadata intact; presentation and embed verification live separately.
export interface Game {
  id: string;
  title: string;
  description: string;
  category: string;
  slug: string;
  imageUrl: string;
  author: string;
  gameUrl: string;
}

export const games: Game[] = [
  {
    id: '1',
    title: 'fly.pieter.com',
    description: 'Free to play MMO flight simulator',
    category: 'Simulation',
    slug: 'fly-pieter',
    imageUrl: '/games/fly_pieter.webp',
    author: 'levelsio',
    gameUrl: 'https://fly.pieter.com',
  },
  {
    id: '2',
    title: 'Combat Mission',
    description: 'Tactical combat simulation',
    category: 'Action',
    slug: 'combat-mission',
    author: 'reaganmaconi',
    imageUrl: '/games/combat_mission.jpeg',
    gameUrl: 'https://combatmission.vercel.app/',
  },
  {
    id: '3',
    title: 'Platform Party',
    description: 'Create, share, and play custom platformer levels!',
    category: 'Multiplayer',
    slug: 'platform-party',
    imageUrl: '/games/platform_party.jpg',
    author: 'javinladish',
    gameUrl: 'https://platformparty.io/play/',
  },
  {
    id: '4',
    title: 'Cybertruck Rocket League',
    description: 'Rocket-powered cybertruck soccer',
    category: 'Sports',
    slug: 'cybertruck-rocket',
    imageUrl: '/games/cybertruck_rocket.webp',
    author: 'rick_boers',
    gameUrl: 'https://rickboers.com/game.html',
  },
  {
    id: '5',
    title: '3D Car Driving Simulator',
    description: 'Realistic 3D driving experience',
    category: 'Simulation',
    slug: '3d-car-simulator',
    imageUrl: '/games/car_simulator.jpeg',
    author: 'ozgrozer',
    gameUrl: 'https://3d-car-driving-simulation.vercel.app',
  },
  {
    id: '6',
    title: '2D GTA',
    imageUrl: '/games/2d_gta.webp',
    description: 'Top down GTA inspired game with procedurally generated maps',
    category: 'Action',
    slug: '2d-gta',
    author: 'marckohlbrugge',
    gameUrl: 'https://gta.marc.io',
  },
  {
    id: '7',
    title: 'Island Survivor',
    imageUrl: '/games/island_survivor.jpg',
    description: 'Survive a crash landing on a desert island',
    category: 'Survival',
    slug: 'island-survivor',
    author: 'jasperdeboer',
    gameUrl: 'https://ja.sperdeboer.nl/island/',
  },
  {
    id: '8',
    title: 'Blocky RTS',
    imageUrl: '/games/aoe_rts.png',
    description: 'Simple block styled real-time strategy game',
    category: 'Strategy',
    slug: 'aoe-rts',
    author: 'HeyItzaMi',
    gameUrl: 'https://aoe-rts.itzami.com/',
  },
  {
    id: '9',
    title: 'Falling Bubbles',
    description: 'Addictive bubble popping game',
    imageUrl: '/games/falling_bubbles.png',
    category: 'Puzzle',
    slug: 'falling-bubbles',
    author: 'sagarsaija',
    gameUrl: 'https://falling-bubbles.vercel.app/',
  },
  {
    id: '10',
    title: 'VibeSail',
    description: 'Relaxing sailing simulation game',
    imageUrl: '/games/vibesail.png',
    category: 'Simulation',
    slug: 'vibesail',
    author: 'iporollo',
    gameUrl: 'https://vibesail.com',
  },
  {
    id: '11',
    title: 'WW2 Dog Fight Arena',
    description: 'Intense WW2 aerial combat simulator',
    imageUrl: '/games/ww2_dogfight.png',
    category: 'Action',
    slug: 'ww2-dogfight',
    author: 'zullo',
    gameUrl: 'https://fly.zullo.fun/',
  },
  {
    id: '12',
    title: 'Soccar',
    description: 'Drive, boost, and score in a fast browser soccer match.',
    category: 'Sports',
    slug: 'soccar',
    imageUrl: '/games/soccar.svg',
    author: 'BlendiByl',
    gameUrl: 'https://soccar-one.vercel.app/',
  },
  {
    id: '13',
    title: 'Salmon Survival',
    description: 'Swim upstream and survive a salmon’s journey.',
    category: 'Survival',
    slug: 'salmon-survival',
    imageUrl: '/games/salmon-survival.svg',
    author: 'yearemias',
    gameUrl: 'https://salmon-survival.vercel.app/',
  },
  {
    id: '14',
    title: 'Hungry Seal',
    description: 'Swim, eat fish, and grow in an endless ocean arcade game.',
    category: 'Arcade',
    slug: 'hungry-seal',
    imageUrl: '/games/hungry-seal.svg',
    author: 'horlesq',
    gameUrl: 'https://hungry-seal.horly.dev/',
  },
  {
    id: '15',
    title: 'Neon Nightfall',
    description: 'Survive waves of glowing enemies in a neon arena.',
    category: 'Action',
    slug: 'neon-nightfall',
    imageUrl: '/games/neon-nightfall.svg',
    author: 'hasibdreamer35',
    gameUrl: 'https://mdhasibul35.github.io/neon-nightfall/',
  },
  {
    id: '16',
    title: 'Flap NYC',
    description: 'Flap through a glowing New York skyline.',
    category: 'Arcade',
    slug: 'flap-nyc',
    imageUrl: '/games/flap-nyc.svg',
    author: 'sara_kumodeck',
    gameUrl: 'https://flapnyc.kumodeck.app/',
  },
  {
    id: '17',
    title: 'Thermopylae',
    description: 'Explore an ancient Spartan campaign in a voxel world.',
    category: 'Action',
    slug: 'thermopylae',
    imageUrl: '/games/thermopylae.svg',
    author: 'linyutai120479',
    gameUrl: 'https://thermopylae-v2.vercel.app/',
  },
  {
    id: '18',
    title: 'Dracula 0',
    description: 'Cross a dark pixel world in a side-scrolling action adventure.',
    category: 'Action',
    slug: 'dracula-0',
    imageUrl: '/games/dracula-0.svg',
    author: 'sbalhatlani',
    gameUrl: 'https://dracula-0.vercel.app/',
  },
  {
    id: '19',
    title: 'Moonlit Spellcaster',
    description: 'Walk a moonlit rampart, charge spells, and hit targets.',
    category: 'Arcade',
    slug: 'moonlit-spellcaster',
    imageUrl: '/games/moonlit-spellcaster.svg',
    author: 'angelfish1445',
    gameUrl: 'https://clubhouse1661.github.io/moonlit-spellcaster/',
  },
  {
    id: '20',
    title: 'Freesbee',
    description: 'Run and jump as a dog to catch flying discs before time runs out.',
    category: 'Arcade',
    slug: 'freesbee',
    imageUrl: '/games/freesbee.svg',
    author: 'Dia_konos',
    gameUrl: 'https://okidoki9903.github.io/Freesbee/',
  },
  {
    id: '21',
    title: 'Orbit Forge',
    description: 'Design a rocket, launch it, and watch its flight toward orbit.',
    category: 'Simulation',
    slug: 'orbit-forge',
    imageUrl: '/games/orbit-forge.svg',
    author: 'The_Bioway',
    gameUrl: 'https://vishalbhoir18.github.io/rocket_orbit_forge/',
  },
  {
    id: '22',
    title: 'DIRTLINE',
    description: 'Ride a dirt bike across a rugged course and keep your balance.',
    category: 'Arcade',
    slug: 'dirtline',
    imageUrl: '/games/dirtline.svg',
    author: 'AlexStLouis10',
    gameUrl: 'https://dirtline.pages.dev/?v=2',
  },
  {
    id: '23',
    title: '3rd Mainland Biker',
    description: 'Choose a display name and race a motorbike across a Lagos bridge.',
    category: 'Arcade',
    slug: 'third-mainland-biker',
    imageUrl: '/games/third-mainland-biker.svg',
    author: 'markessien',
    gameUrl: 'https://3rdmainland.start.ng/',
  },
  {
    id: '24',
    title: 'Ink Dash',
    description: 'Move, shoot, and dash through waves of rogues in a pixel arena.',
    category: 'Action',
    slug: 'ink-dash',
    imageUrl: '/games/ink-dash.svg',
    author: 'iamkushalFx',
    gameUrl: 'https://rajpurohitkushal92.github.io/khnix-game-12/',
  },
  {
    id: '25',
    title: 'Quiet Rooms',
    description: 'Explore surreal rooms beneath changing skies and meet their inhabitants.',
    category: 'Adventure',
    slug: 'quiet-rooms',
    imageUrl: '/games/quiet-rooms.svg',
    author: 'slimer48484',
    gameUrl: 'https://53616d616e746861.github.io/quiet-rooms/',
  },
  {
    id: '26',
    title: 'Kindlekeep TD',
    description: 'Defend a fantasy vale against waves of goblins in a tower defense campaign.',
    category: 'Strategy',
    slug: 'kindlekeep-td',
    imageUrl: '/games/kindlekeep-td.svg',
    author: 'k1zcodes',
    gameUrl: 'https://kindlekeep.vercel.app/',
  },
  {
    id: '27',
    title: 'Pantry Dash',
    description: 'Guide a small mouse through a kitchen maze, collecting cheese while avoiding cats.',
    category: 'Arcade',
    slug: 'pantry-dash',
    imageUrl: '/games/pantry-dash.svg',
    author: 'hasibdreamer35',
    gameUrl: 'https://mdhasibul35.github.io/pantry-dash/',
  },
  {
    id: '28',
    title: 'Mars GT',
    description: 'Drive a car through a winding canyon and switch between Earth and Mars gravity.',
    category: 'Simulation',
    slug: 'mars-gt',
    imageUrl: '/games/mars-gt.svg',
    author: 'AndreiProvkin',
    gameUrl: 'https://mars-gt.vercel.app/',
  },
  {
    id: '29',
    title: 'A71 // GO FOR LAUNCH',
    description: 'Steer and vent a rocket powered car through a night drive challenge.',
    category: 'Arcade',
    slug: 'go-for-launch',
    imageUrl: '/games/go-for-launch.svg',
    author: 'blinkit369',
    gameUrl: 'https://go4launch.grok.me/',
  },
  {
    id: '30',
    title: 'Dust & Lead',
    description: 'Cross a pixel Wild West as an armed outlaw on a side-scrolling mission.',
    category: 'Action',
    slug: 'dust-and-lead',
    imageUrl: '/games/dust-and-lead.svg',
    author: 'inkstaid',
    gameUrl: 'https://inkstaid.github.io/dust-and-lead/',
  },
  {
    id: '31',
    title: 'Faux Ami',
    description: 'Guess the true meaning of French words that look familiar in English.',
    category: 'Puzzle',
    slug: 'faux-ami',
    imageUrl: '/games/faux-ami.svg',
    author: 'JaanV_Tiwari',
    gameUrl: 'https://faux-ami-french-game.vercel.app/',
  },
  {
    id: '32',
    title: 'The Mutual Fun',
    description: 'Guide a business dog through seven rounds of musical chairs in a 3D boardroom.',
    category: 'Arcade',
    slug: 'mutual-fun',
    imageUrl: '/games/mutual-fun.svg',
    author: 'AntiJahiliyah',
    gameUrl: 'https://mutual-self.vercel.app/',
  },
  {
    id: '33',
    title: 'Lava Lasso',
    description: 'Run, jump, and swing across a rising lava pit in a 3D action challenge.',
    category: 'Action',
    slug: 'lava-lasso',
    imageUrl: '/games/lava-lasso.svg',
    author: 'breadswort83287',
    gameUrl: 'https://sloptopia.gooooooooor.chatgpt.site/games/lava-lasso.html?from=sloptopia',
  },
  {
    id: '34',
    title: 'Battle Peaks',
    description: 'Aim and fire across a mountainous battlefield in a local two-player artillery game.',
    category: 'Strategy',
    slug: 'battle-peaks',
    imageUrl: '/games/battle-peaks.svg',
    author: 'NeuralOrbitX',
    gameUrl: 'https://battle-peaks1.vercel.app/',
  },
  {
    id: '35',
    title: 'Stardust Isles',
    description: 'Explore a colorful 3D island village and set out on a collecting adventure.',
    category: 'Adventure',
    slug: 'stardust-isles',
    imageUrl: '/games/stardust-isles.svg',
    author: 'DanzerChan',
    gameUrl: 'https://game.danzechen.world/',
  },
  {
    id: '36',
    title: 'Sky Runner',
    description: 'Boost a futuristic car through a neon city in a fast vertical runner.',
    category: 'Arcade',
    slug: 'skyrunner',
    imageUrl: '/games/skyrunner.svg',
    author: 'JohnSlagboom1',
    gameUrl: 'https://games.johnslagboom.com/skyrunner/',
  },
  {
    id: '37',
    title: 'Ski Jumping',
    description: 'Take a training jump and guide a skier down the slope.',
    category: 'Sports',
    slug: 'ski-jumping',
    imageUrl: '/games/ski-jumping.svg',
    author: 'D4fc1o',
    gameUrl: 'https://skijumping.io/',
  },
  {
    id: '38',
    title: 'Dlicom Attack',
    description: 'Fight through network nodes in a turn-based bot battle.',
    category: 'Strategy',
    slug: 'dlicom-attack',
    imageUrl: '/games/dlicom-attack.svg',
    author: 'Chaos_dev_',
    gameUrl: 'https://dlicom-attack.vercel.app/',
  },
  {
    id: '39',
    title: 'DliClips Rush',
    description: 'Tap through a rapid series of clip challenges.',
    category: 'Arcade',
    slug: 'dliclips-rush',
    imageUrl: '/games/dliclips-rush.svg',
    author: 'borsch737',
    gameUrl: 'https://dliclips-rush.netlify.app/',
  },
  {
    id: '40',
    title: 'Little Lake (Gone Fishin\')',
    description: 'Cast a line, wait for a bite, and reel in a fish.',
    category: 'Simulation',
    slug: 'little-lake',
    imageUrl: '/games/little-lake.svg',
    author: 'anzyxZ',
    gameUrl: 'https://fishing-supdlicomcom.vercel.app/',
  },
  {
    id: '41',
    title: 'Ashen Vow',
    description: 'Explore a dark fantasy world and fight its enemies.',
    category: 'Action',
    slug: 'ashen-vow',
    imageUrl: '/games/ashen-vow.svg',
    author: 'KennethRow73543',
    gameUrl: 'https://pearl-spark-hazel-bold.grok.me/',
  },
  {
    id: '42',
    title: 'Nushi Fishing',
    description: 'Cast into a rainy fishing pool and try to reel in its elusive catch.',
    category: 'Simulation',
    slug: 'nushi-fishing',
    imageUrl: '/games/nushi-fishing.svg',
    author: 'takaakiftw',
    gameUrl: 'https://nushizuri02.netlify.app/',
  },
  {
    id: '43',
    title: 'Time Echo',
    description: 'Explore a 3D room, find a hidden memory, and move through repeating cycles.',
    category: 'Adventure',
    slug: 'time-echo',
    imageUrl: '/games/time-echo.svg',
    author: 'MaxSM117',
    gameUrl: 'https://time-echo-play.vercel.app/',
  },
  {
    id: '44',
    title: 'Church Life',
    description: 'Create a character and meet the people of Grace Avenue in a story game.',
    category: 'Adventure',
    slug: 'church-life',
    imageUrl: '/games/church-life.svg',
    author: 'LesediChingwena',
    gameUrl: 'https://churchlife.netlify.app/',
  },
  {
    id: '45',
    title: 'Ripple Pool',
    description: 'Launch colored drops into a pool and merge matching colors.',
    category: 'Puzzle',
    slug: 'ripple-pool',
    imageUrl: '/games/ripple-pool.svg',
    author: 'michaelirizarry',
    gameUrl: 'https://ripplepool.app/',
  },
  {
    id: '46',
    title: 'Proposed Frontiers',
    description: 'Paint and assign territories on a historical map of the Near East.',
    category: 'Strategy',
    slug: 'sykes-picot',
    imageUrl: '/games/proposed-frontiers.svg',
    author: 'Ned_Donovan',
    gameUrl: 'https://sykespicot.io/',
  },
  {
    id: '47',
    title: 'Señor Inteligente',
    description: 'Lasso the signs in a satirical side-scrolling arcade game.',
    category: 'Arcade',
    slug: 'senor-inteligente',
    imageUrl: '/games/senor-inteligente.svg',
    author: 'wirelyss',
    gameUrl: 'https://inteligente.lol/',
  },
  {
    id: '48',
    title: 'Snowboard Supreme',
    description: 'Carve down an endless snowy mountain and build a high score.',
    category: 'Sports',
    slug: 'snowboard-supreme',
    imageUrl: '/games/snowboard-supreme.svg',
    author: 'kidkenney',
    gameUrl: 'https://snowboard-supreme.vercel.app/',
  },
  {
    id: '49',
    title: 'Trip_Ibadan',
    description: 'Drive a passenger route through a stylized Nigerian city.',
    category: 'Simulation',
    slug: 'trip-ibadan',
    imageUrl: '/games/trip-ibadan.svg',
    author: 'drix_man',
    gameUrl: 'https://trip-ibadan.vercel.app/',
  },
  {
    id: '50',
    title: 'Project Nova',
    description: 'Dodge and shoot through waves in a neon space runner.',
    category: 'Arcade',
    slug: 'project-nova',
    imageUrl: '/games/project-nova.svg',
    author: 'TheExaltedOne',
    gameUrl: 'https://project-nova-v0001.grok.me/',
  },
  {
    id: '51',
    title: 'Dili Cart',
    description: 'Race a colorful circuit as a guest and overtake rival drivers.',
    category: 'Sports',
    slug: 'dili-cart',
    imageUrl: '/games/dili-cart.svg',
    author: '00xmado',
    gameUrl: 'https://dili-cart.pages.dev/',
  },
  {
    id: '52',
    title: 'Plaid Circuit',
    description: 'Choose a car and race laps around an arcade circuit.',
    category: 'Sports',
    slug: 'plaid-circuit',
    imageUrl: '/games/plaid-circuit.svg',
    author: 'PolymarketPoke',
    gameUrl: 'https://roadster.grok.me/',
  },
  {
    id: '53',
    title: 'Heroes Journey',
    description: 'Fight your way along a colorful wildwood road.',
    category: 'Action',
    slug: 'heroes-journey',
    imageUrl: '/games/heroes-journey.svg',
    author: 'MemesVsMachine',
    gameUrl: 'https://heroezjourney.com/',
  },
  {
    id: '54',
    title: 'ASH LINE',
    description: 'Defend a wasteland route against zombie waves.',
    category: 'Strategy',
    slug: 'ash-line',
    imageUrl: '/games/ash-line.svg',
    author: 'duoenetziuh',
    gameUrl: 'https://cedar-crisp-sky-orbit.grok.me/ash-line.html',
  },
  {
    id: '55',
    title: 'Sadie & Luna',
    description: 'Help two dogs find their way home through playful challenges.',
    category: 'Puzzle',
    slug: 'sadie-and-luna',
    imageUrl: '/games/sadie-and-luna.svg',
    author: 'julzfol1923',
    gameUrl: 'https://sadieandluna-thegame.grok.me/',
  },
  {
    id: '56',
    title: 'K-DUDU: Ironfang',
    description: 'Move and fight through a pixel-art action stage.',
    category: 'Action',
    slug: 'k-dudu-ironfang',
    imageUrl: '/games/k-dudu-ironfang.svg',
    author: 'Kronodudu',
    gameUrl: 'https://oasis-winter-blade-thunder.grok.me/',
  },
];
