// Canonical catalog copied from iporollo/addictinggames.ai at c2b7d91.
// Keep original metadata intact; presentation and embed verification live separately.
export interface Game {
  id: string;
  title: string;
  description: string;
  category: string;
  slug: string;
  imageUrl: string;
  author: string;
  gameUrl: string;
}

export const games: Game[] = [
  {
    id: '1',
    title: 'fly.pieter.com',
    description: 'Free to play MMO flight simulator',
    category: 'Simulation',
    slug: 'fly-pieter',
    imageUrl: '/games/fly_pieter.webp',
    author: 'levelsio',
    gameUrl: 'https://fly.pieter.com',
  },
  {
    id: '2',
    title: 'Combat Mission',
    description: 'Tactical combat simulation',
    category: 'Action',
    slug: 'combat-mission',
    author: 'reaganmaconi',
    imageUrl: '/games/combat_mission.jpeg',
    gameUrl: 'https://combatmission.vercel.app/',
  },
  {
    id: '3',
    title: 'Platform Party',
    description: 'Create, share, and play custom platformer levels!',
    category: 'Multiplayer',
    slug: 'platform-party',
    imageUrl: '/games/platform_party.jpg',
    author: 'javinladish',
    gameUrl: 'https://platformparty.io/play/',
  },
  {
    id: '4',
    title: 'Cybertruck Rocket League',
    description: 'Rocket-powered cybertruck soccer',
    category: 'Sports',
    slug: 'cybertruck-rocket',
    imageUrl: '/games/cybertruck_rocket.webp',
    author: 'rick_boers',
    gameUrl: 'https://rickboers.com/game.html',
  },
  {
    id: '5',
    title: '3D Car Driving Simulator',
    description: 'Realistic 3D driving experience',
    category: 'Simulation',
    slug: '3d-car-simulator',
    imageUrl: '/games/car_simulator.jpeg',
    author: 'ozgrozer',
    gameUrl: 'https://3d-car-driving-simulation.vercel.app',
  },
  {
    id: '6',
    title: '2D GTA',
    imageUrl: '/games/2d_gta.webp',
    description: 'Top down GTA inspired game with procedurally generated maps',
    category: 'Action',
    slug: '2d-gta',
    author: 'marckohlbrugge',
    gameUrl: 'https://gta.marc.io',
  },
  {
    id: '7',
    title: 'Island Survivor',
    imageUrl: '/games/island_survivor.jpg',
    description: 'Survive a crash landing on a desert island',
    category: 'Survival',
    slug: 'island-survivor',
    author: 'jasperdeboer',
    gameUrl: 'https://ja.sperdeboer.nl/island/',
  },
  {
    id: '8',
    title: 'Blocky RTS',
    imageUrl: '/games/aoe_rts.png',
    description: 'Simple block styled real-time strategy game',
    category: 'Strategy',
    slug: 'aoe-rts',
    author: 'HeyItzaMi',
    gameUrl: 'https://aoe-rts.itzami.com/',
  },
  {
    id: '9',
    title: 'Falling Bubbles',
    description: 'Addictive bubble popping game',
    imageUrl: '/games/falling_bubbles.png',
    category: 'Puzzle',
    slug: 'falling-bubbles',
    author: 'sagarsaija',
    gameUrl: 'https://falling-bubbles.vercel.app/',
  },
  {
    id: '10',
    title: 'VibeSail',
    description: 'Relaxing sailing simulation game',
    imageUrl: '/games/vibesail.png',
    category: 'Simulation',
    slug: 'vibesail',
    author: 'iporollo',
    gameUrl: 'https://vibesail.com',
  },
  {
    id: '11',
    title: 'WW2 Dog Fight Arena',
    description: 'Intense WW2 aerial combat simulator',
    imageUrl: '/games/ww2_dogfight.png',
    category: 'Action',
    slug: 'ww2-dogfight',
    author: 'zullo',
    gameUrl: 'https://fly.zullo.fun/',
  },
  {
    id: '12',
    title: 'Soccar',
    description: 'Drive, boost, and score in a fast browser soccer match.',
    category: 'Sports',
    slug: 'soccar',
    imageUrl: '/games/soccar.svg',
    author: 'BlendiByl',
    gameUrl: 'https://soccar-one.vercel.app/',
  },
  {
    id: '13',
    title: 'Salmon Survival',
    description: 'Swim upstream and survive a salmon’s journey.',
    category: 'Survival',
    slug: 'salmon-survival',
    imageUrl: '/games/salmon-survival.svg',
    author: 'yearemias',
    gameUrl: 'https://salmon-survival.vercel.app/',
  },
  {
    id: '14',
    title: 'Hungry Seal',
    description: 'Swim, eat fish, and grow in an endless ocean arcade game.',
    category: 'Arcade',
    slug: 'hungry-seal',
    imageUrl: '/games/hungry-seal.svg',
    author: 'horlesq',
    gameUrl: 'https://hungry-seal.horly.dev/',
  },
  {
    id: '15',
    title: 'Neon Nightfall',
    description: 'Survive waves of glowing enemies in a neon arena.',
    category: 'Action',
    slug: 'neon-nightfall',
    imageUrl: '/games/neon-nightfall.svg',
    author: 'hasibdreamer35',
    gameUrl: 'https://mdhasibul35.github.io/neon-nightfall/',
  },
  {
    id: '16',
    title: 'Flap NYC',
    description: 'Flap through a glowing New York skyline.',
    category: 'Arcade',
    slug: 'flap-nyc',
    imageUrl: '/games/flap-nyc.svg',
    author: 'sara_kumodeck',
    gameUrl: 'https://flapnyc.kumodeck.app/',
  },
  {
    id: '17',
    title: 'Thermopylae',
    description: 'Explore an ancient Spartan campaign in a voxel world.',
    category: 'Action',
    slug: 'thermopylae',
    imageUrl: '/games/thermopylae.svg',
    author: 'linyutai120479',
    gameUrl: 'https://thermopylae-v2.vercel.app/',
  },
  {
    id: '18',
    title: 'Dracula 0',
    description: 'Cross a dark pixel world in a side-scrolling action adventure.',
    category: 'Action',
    slug: 'dracula-0',
    imageUrl: '/games/dracula-0.svg',
    author: 'sbalhatlani',
    gameUrl: 'https://dracula-0.vercel.app/',
  },
  {
    id: '19',
    title: 'Moonlit Spellcaster',
    description: 'Walk a moonlit rampart, charge spells, and hit targets.',
    category: 'Arcade',
    slug: 'moonlit-spellcaster',
    imageUrl: '/games/moonlit-spellcaster.svg',
    author: 'angelfish1445',
    gameUrl: 'https://clubhouse1661.github.io/moonlit-spellcaster/',
  },
  {
    id: '20',
    title: 'Freesbee',
    description: 'Run and jump as a dog to catch flying discs before time runs out.',
    category: 'Arcade',
    slug: 'freesbee',
    imageUrl: '/games/freesbee.svg',
    author: 'Dia_konos',
    gameUrl: 'https://okidoki9903.github.io/Freesbee/',
  },
  {
    id: '21',
    title: 'Orbit Forge',
    description: 'Design a rocket, launch it, and watch its flight toward orbit.',
    category: 'Simulation',
    slug: 'orbit-forge',
    imageUrl: '/games/orbit-forge.svg',
    author: 'The_Bioway',
    gameUrl: 'https://vishalbhoir18.github.io/rocket_orbit_forge/',
  },
];
