export const games: Game[] = [
  {
    id: '1',
    title: 'fly.pieter.com',
    description: 'Free to play MMO flight simulator',
    category: 'Simulation',
    slug: 'fly-pieter',
    imageUrl: '/games/fly_pieter.webp',
    author: 'levelsio',
    gameUrl: 'https://fly.pieter.com',
  },
  {
    id: '2',
    title: 'Combat Mission',
    description: 'Tactical combat simulation',
    category: 'Action',
    slug: 'combat-mission',
    author: 'reaganmaconi',
    imageUrl: '/games/combat_mission.jpeg',
    gameUrl: 'https://combatmission.vercel.app/',
  },
  {
    id: '3',
    title: 'Platform Party',
    description: 'Create, share, and play custom platformer levels!',
    category: 'Multiplayer',
    slug: 'platform-party',
    imageUrl: '/games/platform_party.jpg',
    author: 'javinladish',
    gameUrl: 'https://platformparty.io/play/',
  },
  {
    id: '4',
    title: 'Cybertruck Rocket League',
    description: 'Rocket-powered cybertruck soccer',
    category: 'Sports',
    slug: 'cybertruck-rocket',
    imageUrl: '/games/cybertruck_rocket.webp',
    author: 'rick_boers',
    gameUrl: 'https://rickboers.com/game.html',
  },
  {
    id: '5',
    title: '3D Car Driving Simulator',
    description: 'Realistic 3D driving experience',
    category: 'Simulation',
    slug: '3d-car-simulator',
    imageUrl: '/games/car_simulator.jpeg',
    author: 'ozgrozer',
    gameUrl: 'https://3d-car-driving-simulation.vercel.app',
  },
  {
    id: '6',
    title: '2D GTA',
    imageUrl: '/games/2d_gta.webp',
    description: 'Top down GTA inspired game with procedurally generated maps',
    category: 'Action',
    slug: '2d-gta',
    author: 'marckohlbrugge',
    gameUrl: 'https://gta.marc.io',
  },
  {
    id: '7',
    title: 'Island Survivor',
    imageUrl: '/games/island_survivor.jpg',
    description: 'Survive a crash landing on a desert island',
    category: 'Survival',
    slug: 'island-survivor',
    author: 'jasperdeboer',
    gameUrl: 'https://ja.sperdeboer.nl/island/',
  },
  {
    id: '8',
    title: 'Blocky RTS',
    imageUrl: '/games/aoe_rts.png',
    description: 'Simple block styled real-time strategy game',
    category: 'Strategy',
    slug: 'aoe-rts',
    author: 'HeyItzaMi',
    gameUrl: 'https://aoe-rts.itzami.com/',
  },
];
